### ISSUE TITLE
[Bug][Dialog] Pressing the Esc button does not close the Dialog

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#519]
**Describe the bug**
Pressing the Escape button should close the Dialog: https://www.telerik.com/kendo-vue-ui/components/dialogs/dialog/keyboard-navigation

**To Reproduce**
1. Open this stackblitz and click "Open Dialog": https://stackblitz.com/edit/cevnff?file=src%2Fmain.vue
2. Press Escape and notice that nothing happens

**Expected behavior**
Pressing Escape should close the Dialog.

Reported in Ticket ID: 1640920

**Comment by zdravkov** [comment]
The issue is fixed in v4.3.1 of Kendo UI for Vue - https://stackblitz.com/edit/cevnff-ytxd5k?file=src%2Fmain.vue

**Comment by kdikov82** [comment]
The issue is still present in version 4.3.1 (if you don't click within the Dialog after opening it):
https://stackblitz.com/edit/dc6cws?file=package.json,src%2Fmain.js
